
#spring:
#  application:
#    name: msf-provider
server:
  port: 8889


mybatis:
  mapper-locations: classpath*:com/wb/**/mapper/*Mapper.xml
  configuration:
      map-underscore-to-camel-case: true
spring:
  application:
    name: msf-verify
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/msf?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
   basic:
      enabled: false
   user:
     name: wb
     password: 123456
  redis:
    host: 192.168.79.135
    password:
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka01:7001/eureka/,http://eureka02:7002/eureka/
  instance:
  #注册名称
    instance-id: msf-verify
  #注册显示ip
    prefer-ip-address: true
info:
 app.name: msf-verify
 company.name: wangbin
jwt:
  secret: JWT_SECRET
  expiration: 86400
