server:
  port: 80

provider:
 url: http://MSF-PROVIDER/

spring:
  application:
    name: msf-consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/msf?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  security:
    basic:
    enabled: false
    user:
         name: wb
         password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka01:7001/eureka/,http://eureka02:7002/eureka/
info:
 app.name: msf-consumer
 company.name: wangbin